### ISSUE TITLE
How Sonic-restapi is different from sonic-mgmt-framework?

### ISSUE THREAD

**Issue by amareshpGithub** [Azure/sonic-restapi#100]
Hi folks,

I have a basic query related to sonic-restapi.
What I understood is, sonic-mgmt-framework run the rest server and through rest client, using this container we can configure the redis DB.
If that is so, what is the use of sonic-restapi ?

Thanks,
Amaresh

**Comment by prsunny** [comment]
sonic-mgmt-framework supports overall management of Sonic OS and has the capability of configurations/validation/get/set of various features. sonic-restapi currently supports configuring a limited set of Sonic configurations, like VNET, Static routes and was developed earlier than sonic-mgmt-framework.
